### PR TITLE
Add Getting started section

### PR DESCRIPTION
**Pull request by jhryniuk**

### CODE REVIEW

**Comment by jhryniuk** [comment]
CR please

**Comment by jhryniuk** [comment]
@partikus ping @dominikpgs ping

**Comment by partikus** [comment]
@jhryniuk we have to update this pr after #24 merge, please let me know if you need some clarifications

**Comment by partikus** [comment]
Closed in favor of sample-projects placed [here](https://github.com/PGS-php/php-docker-skeleton-integration)

**Pull request closed without merging**
